### PR TITLE
Github Actions Workflow

### PR DESCRIPTION
**Pull request by zeljkobekcic**
I started to create a workflow to automate the tests. There is still something not working correct, so it's a WIP.

### CODE REVIEW

**Comment by zeljkobekcic** [comment]
Currently the tests fail inside the action. I don't understand why yet.

**Comment by mattmc3** [comment]
I love this, thank you! I hadn't gotten there yet, but it was high on my list. I really dig the help.

**Comment by mattmc3** [comment]
Also, when you get it working, can you squash the commits? Seems like we probably only need one final commit for this one and not all the trial and error leading up to get CI working.

**Comment by zeljkobekcic** [comment]
To me the tests in the pipeline fail because of some setup in this test here:

https://github.com/zeljkobekcic/antidote/blob/main/tests/test_bundle.zsh#L1.

Here it clearly says:

```
# === test_bundle ===
# temp ANTIDOTE_HOME=
```

This indicates to me, that something did not work. I am sorry, but my ZSH skills are not good enough to understand what is happening there. Can you help me?

**Comment by mattmc3** [comment]
Is it possible that cloning ZTAP didn't work? https://github.com/zeljkobekcic/antidote/blob/06847f733f2a4c75e917be8063e234b71e39bcdb/tests/runtests#L14-L15

Should the clone be added to the workflow? I don't have time right now to look too deeply into it, but this is a good start. I'll try to revisit soon.

**Comment by zeljkobekcic** [comment]
I have looked into into it a little more. ZTAP is cloned correctly, but these temp directories are not setup correctly I think. I guess the error is in these lines of code:

```sh
0=${(%):-%x}
@echo "=== ${0:t:r} ==="

autoload -Uz ${0:a:h}/functions/setup && setup
```

I have no clue what is happening here.

**Comment by mattmc3** [comment]
@zeljkobekcic - I finally got back around to this, and am hacking away on a feature branch that has a working CI workflow. Thanks for getting me started here. I'm going to close this PR and go the other route with this new branch: https://github.com/mattmc3/antidote/tree/feat-refactor-tests-for-ci

**Pull request closed without merging**
